steps:

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'RicardoMelloKIM'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'

- task: DownloadGitHubRelease@0
  inputs:
    connection: 'RicardoMelloKIM'
    userRepository: 'AutomacaoITQC/AutomacaoQA'
    defaultVersionType: 'latest'
    downloadPath: '$(System.ArtifactsDirectory)'