steps:

# Execute the download to the Azure Repos
- task: DownloadGitHubRelease@0
  inputs:
    connection: 'RicardoMelloKIM'
    userRepository: 'AutomacaoITQC/AutomacaoQA'
    defaultVersionType: 'latest'
    #version: '2.8.6'
    downloadPath: '$(System.ArtifactsDirectory)'