steps:

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'RicardoMelloKIM'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'