steps:
- task: DownloadGitHubRelease@0
  inputs:
    connection: 'RicardoMelloKIM'
    userRepository: 'AutomacaoITQC/AutomacaoQA'
    defaultVersionType: 'latest'
    downloadPath: '$(System.ArtifactsDirectory)'
    version: '2.8.7'